-- WARNING: Do NOT edit the input and output ports in this file in a text
-- editor if you plan to continue editing the block that represents it in
-- the Block Editor! File corruption is VERY likely to occur.

-- Copyright (C) 1991-2013 Altera Corporation
-- Your use of Altera Corporation's design tools, logic functions
-- and other software and tools, and its AMPP partner logic
-- functions, and any output files from any of the foregoing
-- (including device programming or simulation files), and any
-- associated documentation or information are expressly subject
-- to the terms and conditions of the Altera Program License
-- Subscription Agreement, Altera MegaCore Function License
-- Agreement, or other applicable license agreement, including,
-- without limitation, that your use is for the sole purpose of
-- programming logic devices manufactured by Altera and sold by
-- Altera or its authorized distributors.  Please refer to the
-- applicable agreement for further details.


-- Generated by Quartus II 64-Bit Version 13.0 (Build Build 232 06/12/2013)
-- Created on Sun May 23 11:20:16 2021

LIBRARY ieee;
USE ieee.std_logic_1164.all;


--  Entity Declaration

ENTITY clk10khzdiv_test IS
-- {{ALTERA_IO_BEGIN}} DO NOT REMOVE THIS LINE!
PORT
(
clk_25m : IN STD_LOGIC;
clk10khz : OUT STD_LOGIC;

signal clk10kdiv:inout integer range 0 to 2500
);
-- {{ALTERA_IO_END}} DO NOT REMOVE THIS LINE!

END clk10khzdiv_test;


--  Architecture Body

ARCHITECTURE clk10khzdiv_test_architecture OF clk10khzdiv_test IS


BEGIN

	process(clk_25m)
	begin
		if(clk_25m'event and clk_25m='1') then
			case clk10kdiv is
			when 1000 =>
				clk10khz<='1';
				clk10kdiv<=clk10kdiv+1;
			when 2500 =>
				clk10khz<='0';
				clk10kdiv<=0;			--uzstadit 20kHz signalu uz 0
			when others =>
				clk10kdiv<=clk10kdiv+1;
			end case;
		end if;		
			
	end process;


END clk10khzdiv_test_architecture;
